---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

spicenet:
  validator:
    source_url: https://github.com/pepper-research/testnet-canary/releases/download
    configs_source_url: https://github.com/pepper-research/testnet-canary
    ports:
      http_port: 12346
      metrics_port: 9186
