---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    spicenet:
      hosts:
        validator.spicenet.testnet.encapsulate.xyz:
          type: validator
